services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./postgres/config/init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  test_task:
    container_name: test_task
    image: youdzhin/test-task
    ports:
      - "80:8080"
    depends_on:
      - postgres
      - pgadmin
    networks:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped



networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: