spring:
  application:
    name: test-task
  datasource:
    url: jdbc:postgresql://postgres:5432/spring_yandex_test_task
    password: password
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 8080